export {default as HomePage} from './Home'
export {default as LoginPage} from './Login'
export {default as Page1} from './Page1'
export {default as Page2} from './Page2'
export {default as SignUpPage} from './SignUp'
export {default as UserprofilePage} from './Userprofile'
