import React from 'react'

function Dash() {
  return (
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem aliquam, quasi nobis modi dignissimos pariatur provident tempore voluptates atque nulla? Soluta, magnam voluptates, ipsam ducimus impedit eos fugiat consequatur est, commodi magni nulla reprehenderit alias earum necessitatibus recusandae dolorem id distinctio perspiciatis autem et neque delectus! Reprehenderit debitis voluptas iste amet dicta, necessitatibus eaque enim beatae atque hic excepturi quod accusamus nulla itaque sapiente praesentium velit repudiandae repellendus ducimus quibusdam sint et recusandae optio neque? Assumenda accusamus neque laudantium nobis ut mollitia dolores nesciunt alias at ex, labore ullam dolorem saepe quidem consequatur necessitatibus sunt perspiciatis qui delectus hic quae rerum obcaecati laboriosam! Sint dolorem possimus debitis doloribus pariatur vel sunt soluta amet, consequatur non voluptatibus, laudantium asperiores nobis corporis inventore, autem ipsum eveniet praesentium voluptas itaque similique commodi magni? Dignissimos esse ducimus delectus! Nisi provident autem commodi nulla facilis a est! Optio inventore voluptatum unde odio, esse sit reiciendis harum consectetur, quisquam et dignissimos ad laboriosam aperiam soluta blanditiis a vitae voluptatem? Laudantium id error alias aut eligendi culpa obcaecati dicta voluptas dolorum ullam sunt est quae tenetur iure nobis suscipit sequi magni ducimus tempora amet molestiae, esse harum sapiente et. Nam iste, quisquam soluta eaque harum totam perspiciatis eius dicta alias aliquam vero ex laborum, adipisci quod quas qui maiores delectus vel. Repellat, tempore possimus distinctio excepturi at eos molestiae impedit voluptas, aperiam quis pariatur voluptate sint nulla rerum, reprehenderit non deleniti. Quo unde, neque deserunt ad quisquam odit quidem exercitationem, harum voluptas quaerat beatae praesentium dolores fugit? Temporibus, earum vero distinctio tempore nesciunt natus quod reprehenderit est iste, esse facere consequuntur minima veritatis numquam a dignissimos dolorum amet asperiores quo nulla minus praesentium rem error at? Ratione enim neque architecto unde ullam explicabo porro adipisci quod a deserunt debitis libero, animi fugit alias, magnam ipsam officia. Nesciunt.
    </div>
  )
}

export default Dash